---

title: "research exceptions during TCObject.resolveArrayReference()"
layout: issue
tags: 
permalink: /browse/CDV-400

issue_key: CDV-400
issue_numeric_sort_key: 400
issuetype: "Bug"
project: "Community Development (Terracotta Server)"
project_key: "CDV"
status: "Closed"
resolution: "Fixed"
priority: "2 Major"
components: "DSO:L1"
labels: 
assignee: "teck"
reporter: "teck"
votes:  0
watchers: 0

created: "2007-08-27T17:51:00.000-0400"
updated: "2007-10-29T16:47:02.000-0400"
resolved: "2007-10-16T18:29:14.000-0400"

---



{% raw %}



## Description

<div markdown="1" class="description">

I don't know for sure if this broken, but I suspect it is. If TCObejct.resolveArrayReference() throws an exception, the artificial synchronized block on the resolveLock will fail to complete, probably earning oneself an IllegalMonitorStateException when the containing method exits. 

The instrumentation in question is in TransparencyCodeAdpater.visitInsn() for the AALOAD case.

</div>

## Comments


{:.comment-heading}
### **Tim Eck** <span class="date">2007-10-16</span>

<div markdown="1" class="comment">

This is indeed broken, but I can't think of a good way to fix it without some really funky/horrible bytecode OR figuring out a way to know the precise type of the array dereference so that we can generate method to do the resolve in a controlled manner (and maybe more hotspot friendly)

Either way, I think I'm going to close this "research" item and enter a real bug about it



</div>



{% endraw %}
