---

title: "Standardize behaviors when threads fail on attempting cluster operations after shutdown"
layout: issue
tags: 
permalink: /browse/CDV-1562

issue_key: CDV-1562
issue_numeric_sort_key: 1562
issuetype: "Bug"
project: "Community Development (Terracotta Server)"
project_key: "CDV"
status: "Open"
resolution: ""
priority: "2 Major"
components: ""
labels: 
assignee: "cdennis"
reporter: "cdennis"
votes:  0
watchers: 3

created: "2011-03-10T15:52:28.000-0500"
updated: "2012-06-25T15:41:06.000-0400"
resolved: ""

---



{% raw %}



## Description

<div markdown="1" class="description">

The current behavior of throwing TCNotRunningException from toolkit methods (especially locking methods) when there is no active client available causes some strange behaviors in some of the toolkit classes.  One such example (although I imagine there are many others) is that of TerracottaCondition.  If the client associated with a TerracottaCondition is shutdown while a thread is waiting on the condition then on subsequent interruption the lock reacquire will throw a TCNotRunningException.  This exception prevents reacquire of the lock hold, and so the subsequent associated write unlock throws an IllegalMonitorStateException that hides the original exception.

We should attempt to decide what the correct the behavior should be in such strange corner cases.

</div>

## Comments



{% endraw %}
