---

title: "Toolkit BlockingQueue does not honor interrupt if L2 server goes offline"
layout: issue
tags: 
permalink: /browse/CDV-1551

issue_key: CDV-1551
issue_numeric_sort_key: 1551
issuetype: "Bug"
project: "Community Development (Terracotta Server)"
project_key: "CDV"
status: "Open"
resolution: ""
priority: "2 Major"
components: ""
labels: 
assignee: "cdennis"
reporter: "nestrada"
votes:  0
watchers: 4

created: "2011-02-07T09:44:59.000-0500"
updated: "2011-10-11T19:09:13.000-0400"
resolved: ""

---



{% raw %}


## Attachments

* <em>nestrada</em> (3.000 k, text/plain) [BlockingQueueHaltTest.java](/attachments/CDV/CDV-1551/BlockingQueueHaltTest.java)




## Description

<div markdown="1" class="description">

The bug is outlined here.

http://forums.terracotta.org/forums/posts/list/4830.page

In short, when an L2 server goes down, an interrupt request on a toolkit provided BlockingQueue never throws an InterruptedException (for cleanup mostly).

I've traced the problem in the await() method of TerracottaCondition, in a finally block where  reacquireLock(numOfHolds) is invoked. IMO, the latter should check if the current thread is interrupted as it does a couple of lines above before doing any further locking.



</div>

## Comments


{:.comment-heading}
### **Nicolas Estrada** <span class="date">2011-02-07</span>

<div markdown="1" class="comment">

I forgot to mention, I have attached a simple use case. To reproduce the bug, simply start the L2, run the main() of BlockingQueueHaltTest, stop the L2 and watch the paint dry ;)

</div>


{:.comment-heading}
### **Fiona OShea** <span class="date">2011-02-08</span>

<div markdown="1" class="comment">

Is this expected behaviour?

</div>


{:.comment-heading}
### **Chris Dennis** <span class="date">2011-02-09</span>

<div markdown="1" class="comment">

This is not a simple issue.  I don't think we can apply the fix Nicolas suggests in TerracottaCondition since the contract on Condition.await() is such that the locks held on entry must be reacquired on exit, even if this means waiting for the return of a disappeared server.  We might however be able to code a specific fix for the blocking queue interrupt issue since we know in this case that the lock will simply be reacquired only for the InterruptedException to be thrown, and the lock to subsequently released in the queue code.

This isn't something I expect to solve in a Fremantle timeframe however, so I'm going to push this out to Ulloa. 

</div>



{% endraw %}
